### ISSUE TITLE
1

### ISSUE THREAD

**Issue by AIwang666** [nichan-13/Echarts-Demo#1]
为什么不能用VSCODE打开啊

**Comment by nichan-13** [comment]
git clone到本地后使用vscode打开，在index.html使用默认浏览器打开就可以看到了呀，你是什么打不开呢？

**Comment by AIwang666** [comment]
打开了 还有一个问题 我想在地图上添加一个新的中心城市比如长沙应该修改哪里 能使它的名字出现在地图上啊

**Comment by nichan-13** [comment]
你可以查看一下 /js/index.js 中 模拟飞行路线地图 的内容，其中 XAData  XNData  YCData 三个数组都是航线内容，在数组中添加如
 [{
      name: '西安'
    },{
      name: '长沙',
      value: 100
    }]
即可添加从西安到长沙的航线

**Comment by AIwang666** [comment]
是让长沙这个字符出现在地图上 可以显示这个坐标 但是坐标没有对应的名称

**Comment by AIwang666** [comment]
OK 有了 谢谢博主 刚才是我理解错了 感谢！
